accounts/urls.py
from django.conf.urls import url
from .views import *

app_name = 'accounts'

urlpatterns = [

    url(r'^login/$', login_view, name='login'),
    url(r'^register/$', register_view, name="register"),
    url(r'^logout/$', logout_view, name="logout"),

]

blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from home.views import home_view

from django.conf.urls.static import static
from django.conf import  settings


urlpatterns = [

    url(r'^admin/', admin.site.urls),

    url(r'^$', home_view, name='home'),

    url(r'^post/', include('post.urls')),

    url(r'^accounts/', include('accounts.urls')),

]

urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

post/urls.py
from django.conf.urls import url
from .views import *

app_name = 'post'

urlpatterns = [

    url(r'^index/$', post_index, name='index'),
    url(r'^create/$', post_create, name='create'),
    url(r'^(?P<slug>[\w-]+)/$', post_detail, name='detail'),      # d+ regular expressions means that it can include many digits
    url(r'^(?P<slug>[\w-]+)/update/$', post_update, name='update'),
    url(r'^(?P<slug>[\w-]+)/delete/$', post_delete, name='delete'),
]

home/views.py
from django.shortcuts import render, HttpResponse


def home_view(request):
    if request.user.is_authenticated():
        context = {
            'isim': 'Umedzhon'
        }
    else:
        context = {
            'isim': 'You are my guest'
        }
    return render(request, 'home.html', context)

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8" name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}Umedzhon's Shelve{% endblock %}</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>

    {% include 'messages.html' %}

    {% include "header.html" %}

    {% block body %}

    {% endblock %}


    <script src="{% static "js/jquery.min.js" %}"></script>
    <script src="{% static "js/bootstrap.min.js" %}"></script>

</body>
</html>

templates/header.html
<!-- Navbar Start -->
<nav class="navbar navbar-inverse navbar-fixed-top" role="banner">
    <div class="container">

        <div class="navbar-header">

            <!-- Telefon ekranları için menü butonu -->
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>

            <!-- İsim Soyisim veya Marka İsmi -->
            <a href="{% url 'home' %}" class="navbar-brand">Umedzhon Izbasarov</a>
        </div>

        <nav class="collapse navbar-collapse" role="navigation">

            <!-- Arama Çubuğu -->
            <form class="navbar-form navbar-left" role="search" method="GET" action="">
                <div class="input-group">
                    <input class="form-control" type="text" name="q" placeholder="Search on blog" value="{{request.GET.q}}" >
                    <span class="input-group-btn">
                        <input class="btn btn-default" type="submit" value="Search">
                    </span>
                </div>
            </form>

            <!-- Temel Sayfalar -->
            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}
                    <li><a href="{% url 'post:create' %}" >Create Post</a></li>
                {% endif %}
                <li><a href="{% url 'home' %}">Home</a></li>
                <li><a href="{% url 'post:index' %}">Posts</a></li>
                <li><a href="#">About Me</a></li>
                <li><a href="#">Contact</a></li>


                 {% if not request.user.is_authenticated %}
                    <li><a href="{% url 'accounts:register' %}">Sign up</a></li>
                    <li><a href="{% url 'accounts:login' %}">Sign in</a></li>
                {% else %}
                    <li><a href="{% url 'accounts:logout' %}">Sign out </a></li>
                {% endif %}
            </ul>

        </nav>

    </div>
</nav>

templates/home.html
{% extends 'base.html' %}

{% block title %}
    Anasayfa - {{ block.super }}
{% endblock %}

{% block body %}
    <div class="container-fluid">
     <div class="row" style="margin-bottom: 30px;">
         <div class="col-md-5 col-sm-6" style="background-color: #ff0000;margin-left: 75px; height: 150px;">1. Post</div>
         <div class="col-md-5 col-sm-6" style="background-color: #ffca11;margin-left: 75px; height: 150px;">2. Post</div>
     </div>

     <div class="row" style="margin-bottom: 30px;">
         <div class="col-md-5 col-sm-6" style="background-color: #ff0000;margin-left: 75px; height: 150px;">3. Post</div>
         <div class="col-md-5 col-sm-6" style="background-color: #ffca11;margin-left: 75px; height: 150px;">4. Post</div>
     </div>

     <div class="row" style="margin-bottom: 30px;">
         <div class="col-md-5 col-sm-6" style="background-color: #ff0000;margin-left: 75px; height: 150px;">5. Post</div>
         <div class="col-md-5 col-sm-6" style="background-color: #ffca11;margin-left: 75px; height: 150px;">6. Post</div>
     </div>

        Welcome {{request.user.get_full_name}}

    </div>
{% endblock %}

templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-success alert-dismissible" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
          {{ message }}
        </div>
    {% endfor %}
{% endif %}